spring.application.name=kiyim-kechak-store

# Server configuration
server.port=${PORT:8080}
server.servlet.context-path=/

# PostgreSQL Database configuration
spring.datasource.url=jdbc:postgresql://localhost:2006/kiyimdokoni_database
spring.datasource.username=postgres
spring.datasource.password=2006
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring Web & Encoding
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.period=0
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
